image: Visual Studio 2019

environment:
  nodejs_version: "18"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

artifacts:
  - path: dist
    name: dist

deploy:
  provider: GitHub
  artifact: dist
  on:
    branch: main