version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: "18"
  GITHUB_TOKEN:
    secure: YOUR_ENCRYPTED_TOKEN_HERE  # Замените на зашифрованный токен

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

on_success:
  - git config --global user.name "GitHub Actions"
  - git config --global user.email "actions@github.com"
  - npm run deploy